"""
Django settings for manage_tasks project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

"""

import os  # Import os module

import os  # Import os module

# Logging configuration

SECRET_KEY = 'your-secure-random-secret-key'  # Replace with a secure random key

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # Define the base directory

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # Define the base directory


STATIC_URL = '/static/'  # URL prefix for static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory to collect static files


STATIC_URL = '/static/'  # URL prefix for static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory to collect static files


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',  # Add the tasks app here
]


ROOT_URLCONF = 'manage_tasks.urls'  # Set the root URL configuration


ALLOWED_HOSTS = ['*']  # Allow all hosts for development

DEBUG = True  # Set DEBUG mode for development



# DeepSeek R1 Model Configuration

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use SQLite as the database engine
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # Path to the SQLite database file
    }
}

DEEPSEEK_API_KEY = "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"
DEEPSEEK_MODEL_NAME = "DeepSeek R1"
GENAI_API_KEY = "AIzaSyBEZggfqPY3tAOxC-DsAMvVMb1yHQv0CsQ"  # Add the API key for the LLM
